name: Dynamic Matrix Builder

on:
  workflow_dispatch:
    inputs:
      alert:
        description: 'Send email if workflow fails'
        default: false
        required: false
        type: boolean

env:
  NEXUS_REPO: nexus.swimlane.io:5000
  GIT_HASH: ${{ github.event.pull_request.head.sha || github.sha }}
  DOT_NET_BASE: swimlane/swimlane-base-dotnet-6.0-sdk
  SWIMLANE_VERSION: 10.8.0

jobs:

  create-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.content }}
    steps:
      - id: matrix 
        run: |
              echo ::set-output name=content::'{"image": ["swimlane/swimlane-backup","swimlane/swimlane-api","swimlane/swimlane-tasks","swimlane/swimlane-reports","swimlane/swimlane-web"]}'

  read-matrix:
    needs:
      - create-matrix
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix: ${{ fromJson(needs.create-matrix.outputs.matrix) }}
      
    steps:
      - name: Type
        run: |
          echo "${{ matrix.image }}"
